// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class CosmeticInformation
{
    public string CosmeticId { get; set; }

    public string CosmeticName { get; set; }

    public string SkinType { get; set; }

    public string ExpirationDate { get; set; }

    public string CosmeticSize { get; set; }

    public decimal DollarPrice { get; set; }

    public string CategoryId { get; set; }

    public virtual CosmeticCategory Category { get; set; }
}