// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class SystemAccount
{
    public int AccountId { get; set; }

    public string AccountPassword { get; set; }

    public string EmailAddress { get; set; }

    public string AccountNote { get; set; }

    public int? Role { get; set; }
}